baseURL = "https://brycewray.com/"
languageCode = "en-us"
title = "BryceWray.com"
theme = "ofotigrid"
googleAnalytics = "UA-126570650-1"

summaryLength = 20
FootnoteReturnLinkContents = "&#8593;"
enableRobotsTXT = true

[params]
    Author = "Bryce Wray"
    Description = "Bryce Wray’s Web site — observations and opinions"

[blackfriday]
    hrefTargetBlank = true

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "About"
        url = "/about/"
        weight = 100
    
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        title = "Posts"
        url = "/posts/"
        weight = 110
