baseURL: https://www.brycewray.com/
languageCode: en-us
title: BryceWray.com
#theme: dart-sass # choices are dart-sass (for embedded), npm-sass, and twcss - as of 2022-03-09
timeZone: America/Chicago

summaryLength: 30 # words --- if you use summaries
FootnoteReturnLinkContents: "&#8593;"
enableRobotsTXT: true
enableGitInfo: true

timeout: "150s" # for the sake of newly generated images and such

pygmentsUseClasses: true

Paginate: 5 # so five posts will appear on each page from "/posts"

params:
  Domain: "brycewray.com"
  Author: "Bryce Wray"
  Description: "Bryce Wray’s website | Observations, opinions, geekiness"
  Host: "CFP" # choices are "CFP" and "Vercel"
  SiteLive: true # Boolean --- used for adapting robots.txt as needed
  SearchTitle: "Search the site"

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - :git
    - lastmod
    - date
    - publishDate
  publishDate:
    - publishDate
    - date

markup:
  highlight:
    guessSyntax: true
    noClasses: false
    tabWidth: 2
  goldmark:
    extensions:
      linkify: false
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true # otherwise, can't use (e.g.) "Content" as a heading
    renderer:
      unsafe: true
      # only to allow for inline HTML and/or JS
      # ... other desired settings are defaults

privacy:
  twitter:
    simple: true

services:
  twitter:
    disableInlineCSS: true

caches:
  getjson:
    dir: :resourceDir/json
    maxAge: 10s
  getresource:
    dir: :resourceDir/_gen
    maxAge: 10s

minify:
  tdewolff:
    html:
      keepQuotes: true
      keepWhitespace: false # per https://discourse.gohugo.io/t/is-html-minification-broken/34174

outputFormats:
  json:
    baseName: "index"
    mediaType: "application/json"
    isPlainText: true

outputs:
  home:
    - html
    - rss
    - json

security:
  funcs:
    getenv:
      - ^*
