#baseURL = "https://brycewray.com" # Change to your site URL and un-comment, of course
languageCode = "en-us" # Change if not appropriate for your site
title = "Site title goes here"

summaryLength = 30 # words --- if you use summaries
FootnoteReturnLinkContents = "&#8593;"
enableRobotsTXT = true

Paginate = 5 # so five posts will appear on each page from "/posts"

[params]
    Author = "Your name goes here"
    Description = "Your site description goes here"

[markup]
    [markup.goldmark]
      [markup.goldmark.parser]
        attribute = true
      [markup.goldmark.renderer]
        unsafe = true # only to allow for inline HTML and/or JS
    [markup.highlight]
      guessSyntax = true
      noClasses = false

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "The obligatory “About me” page"
        url = "/about/"
        weight = 100
    
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        title = "This site’s posts"
        url = "/posts/"
        weight = 110

    [[menu.main]]
        identifier = "privacy"
        name = "Privacy"
        title = "This site’s privacy policy"
        url = "/privacy/"
        weight = 120
