baseURL = "https://brycewray.com/"
languageCode = "en-us"
title = "BryceWray.com"
theme = "ofotigrid"

summaryLength = 30 # words
FootnoteReturnLinkContents = "&#8593;"
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[params]
    Author = "Bryce Wray"
    Description = "Bryce Wray’s Web site — observations and opinions"
    talkyardServerUrl = "https://comments-for-brycewray-com.talkyard.net"
    talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    noreferredLinks = true

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "The About Me page"
        url = "/about/"
        weight = 100
    
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        title = "This site’s posts"
        url = "/posts/"
        weight = 110
