baseURL: https://www.brycewray.com/
languageCode: en-us
title: BryceWray.com
theme: twcss # choices are libsass and twcss - as of 2022-03-03

summaryLength: 30 # words --- if you use summaries
FootnoteReturnLinkContents: "&#8593;"
enableRobotsTXT: true

pygmentsUseClasses: true

Paginate: 5 # so five posts will appear on each page from "/posts"

params:
  Domain: "brycewray.com"
  Author: "Bryce Wray"
  Description: "Bryce Wray’s website | Observations, opinions, geekiness"
  Host: "CFP" # choices are "CFP" and "Vercel"
  SiteLive: true # Boolean --- used for adapting robots.txt as needed

markup:
  goldmark:
    extensions:
      linkify: false
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true # otherwise, can't use (e.g.) "Content" as a heading
    renderer:
      unsafe: true
      # only to allow for inline HTML and/or JS
      # ... other desired settings are defaults
    highlight:
      guessSyntax: true
      noClasses: false

privacy:
  twitter:
    simple: true

services:
  twitter:
    disableInlineCSS: true

caches:
  getjson:
    dir: :resourceDir/json
    maxAge: -1

minify:
  tdewolff:
    html:
      keepQuotes: true
      keepWhitespace: false # per https://discourse.gohugo.io/t/is-html-minification-broken/34174

outputFormats:
  json:
    baseName: "index"
    mediaType: "application/json"
    isPlainText: true

outputs:
  home:
    - html
    - rss
    - json

security:
  funcs:
    getenv:
      - ^*
