# Netlify instructions for my site
#  --  pretty bare-bones setup, but there are other options available
#  --  see https://gohugo.io/hosting-and-deployment/hosting-on-netlify

[build]
    # publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    # HUGO_VERSION = "0.68.3"
    #  --  if you're publishing, use most recent version in last line and uncomment;
    #  --  otherwise, it'll use whatever version Netlify is using, which can be 
    #  --  problematic on occasion
    HUGO_ENV = "production"
    # HUGO_ENABLEGITINFO = "true"
