# Netlify instructions for my site

[build]
    # publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.56.3"
    HUGO_ENV = "production"
    # HUGO_ENABLEGITINFO = "true"