# Netlify instructions for my site

[build]
    # publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.58.3"
    HUGO_ENV = "production"
    # HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/posts/2019/04/why-left-ulysses"
  to = "/posts/2019/05/boxed-in"
  status = 301

[[redirects]]
  from = "/posts/2019/07/why-staying-with-hugo"
  to = "/posts/2019/10/its-about-food-not-decor"
  status = 301

[[redirects]]
  from = "/posts/2019/09/why-left-hugo-eleventy"
  to = "posts/2019/10/its-about-food-not-decor"
  status = 301

[[redirects]]
  from = "/posts/2019/09/back-with-hugo"
  to = "/posts/2019/10/its-about-food-not-decor"
  status = 301