# Netlify instructions for my site

[build]
    # publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.58.3"
    HUGO_ENV = "production"
    # HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/posts/2019/04/why-left-ulysses"
  to = "/posts/2019/05/boxed-in"
  status = 301
