name = "scss-thoreau"
license = "MIT"
description = "SCSS version of twjit-thoreau; originally based on a Hugo theme called “Tale” but now with little resemblance thereto."
min_version = "0.89.0"

tags = ["tags"]

[author]
  name = "Bryce Wray"
  homepage = "https://www.brycewray.com/"

