name = "twjit-hero"
license = "MIT"
description = "Tailwind CSS with JIT; originally based on a Hugo theme called “Tale” but now with little resemblance thereto."
min_version = "0.87.0"

tags = ["tags"]

[author]
  name = "Bryce Wray"
  homepage = "https://www.brycewray.com/"

