name = "Ofotiboot"
license = "MIT"
description = "Variation of a home-made mess, fixed up with Bootstrap 4 per https://discourse.gohugo.io/t/a-step-by-step-tutorial-on-how-to-build-a-bootstrap-based-theme-from-stratch/14886"
min_version = "0.41"

tags = ["tags"]

[author]
  name = "Bryce Wray"
  homepage = "https://brycewray.com/"

