name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'   # every day at 00:00UTC (1900CDT/1800CST)
    - cron: '0 8 * * *'   # every day at 08:00UTC (0300CDT/0200CST)
    - cron: '0 16 * * *'  # every day at 16:00UTC (1100CDT/1000CST)

env:
  HUGO_VERSION: 0.99.1 # will get Extended Version below
  DART_SASS_VERSION: 1.52.1
  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
  TOKEN: ${{ secrets.TOKEN }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
  WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.6.0'
      - name: Install dependencies
        run: npm install
      - name: Download Hugo v${{ env.HUGO_VERSION }}
        run: wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.deb -O hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.deb
      - name: Install Hugo v${{ env.HUGO_VERSION }}
        run: sudo dpkg -i hugo*.deb
      - name: Download Embedded Dart Sass v${{ env.DART_SASS_VERSION }}
        run: curl -LJO https://github.com/sass/dart-sass-embedded/releases/download/${{ env.DART_SASS_VERSION }}/sass_embedded-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
      - name: Unpack Embedded Dart Sass v${{ env.DART_SASS_VERSION }}
        run: |
          tar -xvf sass_embedded-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
          sass_embedded/dart-sass-embedded --version
      - name: Add to the PATH
        run: echo "$GITHUB_WORKSPACE/sass_embedded" >> $GITHUB_PATH
      - name: Build site with Hugo
        run: npm run build # hugo --gc when not using WMs
      - name: Publish to CFP
        uses: cloudflare/pages-action@v1.0.0
        with:
          apiToken: ${{ secrets.CFP_API_TOKEN }}
          accountID: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'hugo-site'
          directory: 'public'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
