on:
  push:
    branches:
      - main

env:
  HUGO_VERSION: 0.99.0 #will get ext version below
  DART_SASS_VERSION: 1.51.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to CFP
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
      - name: Download Hugo v${{ env.HUGO_VERSION }}
        run: "wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.deb -O hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.deb"
      - name: Install Hugo v${{ env.HUGO_VERSION }}
        run: sudo dpkg -i hugo*.deb
      - name: Download Embedded Dart Sass v${{ env.DART_SASS_VERSION }}
        run: "curl -LJO https://github.com/sass/dart-sass-embedded/releases/download/${{ env.DART_SASS_VERSION }}/sass_embedded-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz"
      - name: Install Embedded Dart Sass v${{ env.DART_SASS_VERSION }}
        run: "sudo tar -xvf sass_embedded-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz"
      - name: Build site with Hugo
        run: hugo --gc --minify
      - name: Publish to CFP
        uses: cloudflare/pages-action@v1.0.0
        with:
          apiToken: ${{ secrets.CFP_API_TOKEN }}
          accountID: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'hugo-site'
          directory: 'public'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          TOKEN: ${{ secrets.TOKEN }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
