name: CI-Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@master
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.0
      with:
        hugo-version: '0.75.1'
    - name: Build site with Hugo
      run: hugo --gc --minify --cleanDestinationDir
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}